import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head> {/* Needs to be fixed */}
        <link rel="stylesheet" href="https:[[use.typekit.net/dze2nzm.css"></link>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
